### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by saxenanurag** [CLEpy/clepy-website#11]

**Comment by ghost** [comment]
We have to sign up to get tracking code- is there a preferred admin email we should use to log in?

**Comment by tylerdave** [comment]
We created a new org in GA for CLEpy. 

Tracking code for the website: `UA-112189375-1`

I'll let someone new submit the PR to add it ;-)

Instructions: http://docs.getpelican.com/en/stable/settings.html#GOOGLE_ANALYTICS
