### ISSUE TITLE
Automate refresh of meetup details

### ISSUE THREAD

**Issue by ewdurbin** [CLEpy/clepy-website#24]
I updated the Feb 5th meetup details this morning, nothin happened.

Is there some way to schedule or trigger "build" on our hosting provider when meetup details change?

**Comment by tylerdave** [comment]
Right now the build & deploy are triggered upon a change to the master branch of the repo or by a POST to a webhook URL. I currently have a cron job set up to hit the webhook URL daily but when I noticed your update I ran it manually.

This is probably good enough for now but I'd be open to improvements.

I was thinking zapier might help here but I'm not sure if their "New Event" trigger would happen upon a meetup details change. It would be worth investigating.

**Comment by tylerdave** [comment]
Netlify added scheduled builds so the meetup data is refreshed and the website rebuilt nightly.
